### ISSUE TITLE
Logger library is breaking the server app

### ISSUE THREAD

**Issue by fcastill** [project-flogo/flogo-web#962]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Logger library initialization is breaking the server app.

**Expected behavior**
Application should behave as normally

**Minimal reproduction of the problem with instructions**
1. Start v0.9.0-dev build
2. Open a flow
3. Click log button
4. Server app stops, this error is seen in server console:

```
verbose: [21:36:55.969] updateDB
verbose: [21:36:55.979] updateDB
verbose: [21:36:55.989] updateDB done.
verbose: [21:36:55.989] updateDB done.
verbose: [21:36:55.990] registerActivities success
verbose: [21:36:55.991] registerTriggers success
info: [21:36:56.030] start web server done.
flogo-web::server::ready

  ======================================================
                 ___       __   __   __ TM
                |__  |    /  \ / _` /  \
                |    |___ \__/ \__| \__/

   [success] open http://localhost:3303 in your browser
  ======================================================

/flogo-web/apps/server/node_modules/winston/lib/winston/logger.js:348
    const queryObject = clone(options.query) || {};
                        ^

TypeError: clone is not a function
    at DerivedLogger.query (/flogo-web/apps/server/node_modules/winston/lib/winston/logger.js:348:25)
    at Namespace.io.on.ws (/flogo-web/apps/server/main.js:9030:74)
    at Namespace.emit (events.js:182:13)
    at Namespace.emit (/flogo-web/apps/server/node_modules/socket.io/lib/namespace.js:213:10)
    at /flogo-web/apps/server/node_modules/socket.io/lib/namespace.js:181:14
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

* **Flogo version:** 0.9.0-dev

**Additional information you deem important (e.g. issue happens only occasionally):**
Seems to be related to: https://github.com/winstonjs/winston/issues/1130

**Comment by fcastill** [comment]
Fixed in 91d648a76f7bd406b05824b3a34aba7b06a742cb
